<?php 
function dl_ws_services_resources(){
  return array(
    'payment' => array(
      'retrieve' => array(
        'help' => 'Retrieves a mail from payers',
        'callback' => 'ws_payment',
        'access callback' => 'can_ws_payment',
        'access arguments' => array('view'),
        'access arguments append' => TRUE,
        'args' => array(
        array(
            'name' => 'token',
            'type' => 'string',
            'description' => 'Secret token',
            'source' => array('path' => '0'),
            'optional' => FALSE,
          ),
          
        ),
      ),
    ),
  );
}

function can_ws_payment(){
  return true;
}

function ws_payment($token){
  $items = array();
  $valid = array('payment_received','completed');
  if(!in_array($token,$valid)) return;

  $q = "SELECT DISTINCT users.mail FROM users
    INNER JOIN uc_orders 
    ON uc_orders.uid = users.uid
    AND uc_orders.order_status = '%s'";
  $query = db_query($q,$token);

  while($r = db_fetch_object($query)){
    $items[] = $r->mail;
  }
  return (object)$items;
}
